### ISSUE TITLE
Test ApiRest

### ISSUE THREAD

**Issue by ManuelGallego1** [Samuel05L28/Glamping_Backend#7]
**Requeriments**

- [ ] Try ApiRest For (Cabin, CabinLevel, CabinService, Service, Reservation)
- [x] Load Response Images Of All Methods (Index, Store, Update, Destroy)

**Comment by camgi264** [comment]
![Image](https://github.com/user-attachments/assets/7a0f2353-680e-4344-b351-f7ef4e2537e5)
![Image](https://github.com/user-attachments/assets/230b52df-8728-4b4d-ade0-e48aa57a50a5)
![Image](https://github.com/user-attachments/assets/282d9450-edfa-4adc-ab96-da94e9175f74)
![Image](https://github.com/user-attachments/assets/cb54f53d-2de9-4ec7-8f6f-5e5770930061)
![Image](https://github.com/user-attachments/assets/ce64795d-67aa-4ea9-b89f-604bcb101212)
![Image](https://github.com/user-attachments/assets/5fe778e9-6138-49d9-b9f0-2769dab94317)
![Image](https://github.com/user-attachments/assets/f66f8a68-4318-4d65-b23b-69545e2646b9)
